### ISSUE TITLE
Unable to find Visual Studio

### ISSUE THREAD

**Issue by skipik** [processhacker/processhacker#534]
Just installed MS VS 2017 and MS VS 2019 on one of my PCs and always get this:
```
CustomBuildTool.exe -release
Unable to find Visual Studio.
```
Could you help me to solve the problem?

**Comment by skipik** [comment]
![111](https://user-images.githubusercontent.com/24621645/71534602-f8e20900-2910-11ea-8a58-a1c7b69e8d25.png)
I dunno why it can't find VS as I have two folders in Program Files (x86).
Visual Studio 2017 v15.9.18 & Visual Studio 2019 v16.4.2. Those are the versions I have installed.
It's clean OS also so I doubt there's a problem with OS.

**Comment by dmex** [comment]
I fixed this issue a few weeks ago:
https://github.com/processhacker/processhacker/issues/503

I can't reproduce this right now. You might have to debug the CustomBuildTool?
https://github.com/processhacker/processhacker/tree/master/tools/CustomBuildTool

**Comment by skipik** [comment]
Yeah, I remember that, but looks like its not fixed. :(
I didn't do anything in the OS, just installed those two VS versions.
It's deffo something in new CBT, as I tried to work with some old copy of CBT from october 2019 and it works correcly and finds my visual studio path.
> You might have to debug the CustomBuildTool?

I don't know how to do that at all, sorry. :(

**Comment by skipik** [comment]
I finally find the reason of it.
If you install the latest SDK using this link -> https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk
And UNCHECK 'SDK 18362' during Visual Studio installation you'll have that 'Unable to find Visual Studio' problem.

**Comment by skipik** [comment]
You can try that on a virtual machine.
I fixed it by running the VS Installer, goind to VS 2019 and check 'SDK 18362'. It just updated something and now the CBT works correctly.
So I dunno what causes the probem - your CBT or it's a problem on MS side.

**Comment by dmex** [comment]
> If you install the latest SDK using this link

The build tools are using the official documented COM interface exposed by Visual Studio for detecting the SDK.

> I dunno what causes the probem - your CBT or it's a problem on MS side.

The standalone SDK should be detected by Visual Studio and this is an issue with their code. I'll try report the issue to Microsoft and see what they say.

**Comment by dmex** [comment]
I believe this was fixed in the latest visual studio installer update 👍

**Comment by dmex** [comment]
> This is by design, the Visual Studio setup configuration API won’t detect Windows SDKs that were installed outside the Visual Studio Installer.
