### ISSUE TITLE
When enable GPU performance counter, GPU usage is zero in processes tree list

### ISSUE THREAD

**Issue by lovelifezhenzhen** [processhacker/processhacker#814]
![2021-02-26_100842](https://user-images.githubusercontent.com/39288361/109245148-eae08e80-781a-11eb-8224-6c68a9c7665e.png)

**Comment by jxy-s** [comment]
I don't think the recent change would have broke this, but I'll take a look this weekend.

**Comment by jxy-s** [comment]
Hm @lovelifezhenzhen I'm seeing the GPU column showing properly on my system:
![image](https://user-images.githubusercontent.com/11687482/109372304-15a40480-7866-11eb-8f25-09451e5fc050.png)

You mentioned "GPU performance counter", could you please provide some more information here? What are you expecting to see?

**Comment by jxy-s** [comment]
I think I found what you're speaking about `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` looks to break the updates to the table.

**Comment by lovelifezhenzhen** [comment]
Yes, this happens when I set ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters as 1.

**Comment by dmex** [comment]
This was fixed in the latest nightly build. You can download the update using the Help > Check for updates menu.

Thanks for reporting it 👍

**Comment by MagicAndre1981** [comment]
I still see this in Windows 8.1 (x64). If Perf Counters setting is enabled, GPU usage column is empty. On my 8" tablet win32Bit Win10 20H2 it works with both settings (EnableGpuPerformanceCounters 1 or 0). The column only shows if EnableGpuPerformanceCounters is set to 0.

**Comment by dmex** [comment]
@MagicAndre1981 

> I still see this in Windows 8.1 (x64)

Those counters don't exist on Windows 8. Microsoft only added them recently on Windows 10.

**Comment by MagicAndre1981** [comment]
ok, so maybe also check if counters are supported even when setting is 1? I use portable PH on USB drive and run it on different systems (7, 8.1, 10) with same config XML.

**Comment by dmex** [comment]
@MagicAndre1981 

Good point. I've added a version check for the counters in the latest nightly.

**Comment by MagicAndre1981** [comment]
> Good point. I've added a version check for the counters in the latest nightly.

ok, works, setting is 1 and GPU column shows data in 8.1
